# This file was generated by GoReleaser. DO NOT EDIT.
cask "chv" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "a3210993783bdfc7913b33dca7a701af9f7d302c68d0dd4dd209100ff04b7716"
      url "https://github.com/primissus/agents-hist-viewer/releases/download/v#{version}/chv_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0b7bdb4112302ad442ccc1f2e06efecfcbc462d956c3f2e148ac91e9d0a6b03b"
      url "https://github.com/primissus/agents-hist-viewer/releases/download/v#{version}/chv_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "29b666a7c3013804b4336e4c9baea1f33db1757bc406bcab097f446cc1b862b7"
      url "https://github.com/primissus/agents-hist-viewer/releases/download/v#{version}/chv_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "1a28a1dc5e7fe7e701992150f0eaedd6da4049b9bd9acd26b5a7529feca344ff"
      url "https://github.com/primissus/agents-hist-viewer/releases/download/v#{version}/chv_#{version}_linux_amd64.tar.gz"
    end
  end

  name "chv"
  desc "Search Claude Code, Claude Desktop, Cursor, OpenCode & Codex history from the terminal."
  homepage "https://github.com/primissus/agents-hist-viewer"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "chv"

  # No zap stanza required

  caveats <<~EOS
    Run once to build the search index:
      chv index
  EOS
end
