# This file was generated by GoReleaser. DO NOT EDIT.
cask "chv" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "fa570a0bd648d91c6d23921a7885d7ff4d7aec88eb734e3764bf5cbd39def708"
      url "https://github.com/primissus/agents-hist-viewer/releases/download/v#{version}/chv_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e131f7b7828df8232f3a415294841fd80ab35135c16c87e175070faf80dae28f"
      url "https://github.com/primissus/agents-hist-viewer/releases/download/v#{version}/chv_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "84964bc6a2287cfd8922097dfe9e2bbb7b75a4c6757a6406b6705c0de1eeae37"
      url "https://github.com/primissus/agents-hist-viewer/releases/download/v#{version}/chv_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "0c6f3ebdf34d49535317d83b4f52fa2a9bf64cf208548b07ffc126fa6d3e4242"
      url "https://github.com/primissus/agents-hist-viewer/releases/download/v#{version}/chv_#{version}_linux_amd64.tar.gz"
    end
  end

  name "chv"
  desc "Search Claude Code, Claude Desktop, Cursor, OpenCode & Codex history from the terminal."
  homepage "https://github.com/primissus/agents-hist-viewer"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "chv"

  # No zap stanza required

  caveats <<~EOS
    Run once to build the search index:
      chv index
  EOS
end
