# This file was generated by GoReleaser. DO NOT EDIT.
cask "zjump" do
  version "0.8.0"

  on_macos do
    on_arm do
      sha256 "af00dcd49cee9b4f6718ab5a01bd4f690f4257fcfde61c291f53364fd3fa0487"
      url "https://github.com/primissus/zjump/releases/download/v#{version}/zjump_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/primissus/zjump"
    end
    on_intel do
      sha256 "e61f42fa4847e2a98e734e43b79243147ec188a5e0688566cf03f0de75237f81"
      url "https://github.com/primissus/zjump/releases/download/v#{version}/zjump_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/primissus/zjump"
    end
  end
  on_linux do
    on_arm do
      sha256 "d021753dd49e93b7bf13437f177b4dcb898ccf8e05740fc6dd09d7b902d15b11"
      url "https://github.com/primissus/zjump/releases/download/v#{version}/zjump_#{version}_linux_arm64.tar.gz",
        verified: "github.com/primissus/zjump"
    end
    on_intel do
      sha256 "87743af42926f174306a3df4a8911a427e1e296f5e412cb6e9a23e6f5f29a1c2"
      url "https://github.com/primissus/zjump/releases/download/v#{version}/zjump_#{version}_linux_amd64.tar.gz",
        verified: "github.com/primissus/zjump"
    end
  end

  name "zjump"
  desc "Frecency-based directory-jumping CLI tool (Go reimplementation of zoxide)."
  homepage "https://github.com/primissus/zjump"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zjump"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/zjump"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Add the shell hook to your rc file, e.g.:
      eval "$(zjump init bash)"   # or: zjump init zsh
  EOS
end
