# This file was generated by GoReleaser. DO NOT EDIT.
cask "zjump" do
  version "0.10.0"

  on_macos do
    on_arm do
      sha256 "497ed9aa3418f79a1d97a5180ae184683738ee37104340f7dc3251fd34be05d4"
      url "https://github.com/primissus/zjump/releases/download/v#{version}/zjump_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "08c828279697dc292b0ca9e437ec035baacf4f72e114b7be1cd6974e8c15455c"
      url "https://github.com/primissus/zjump/releases/download/v#{version}/zjump_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e3bc9aef2ec8bfd87bc898dbb15a56b2da31d259d6071dcadca5df5d8e1286a6"
      url "https://github.com/primissus/zjump/releases/download/v#{version}/zjump_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "8983935f9d3b8baf8c089fa82ef722a7bdfafe390fa9891ce6ee7e7b69ad1190"
      url "https://github.com/primissus/zjump/releases/download/v#{version}/zjump_#{version}_linux_amd64.tar.gz"
    end
  end

  name "zjump"
  desc "Frecency-based directory-jumping CLI tool (Go reimplementation of zoxide)."
  homepage "https://github.com/primissus/zjump"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zjump"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/zjump"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Add the shell hook to your rc file, e.g.:
      eval "$(zjump init bash)"   # or: zjump init zsh
  EOS
end
