# This file was generated by GoReleaser. DO NOT EDIT.
cask "zjump" do
  version "0.9.0"

  on_macos do
    on_arm do
      sha256 "228d91368107dd1831c982dfab9a0012ed48fba612bd889fb606d02ee089ba8f"
      url "https://github.com/primissus/zjump/releases/download/v#{version}/zjump_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "2d8b061b98639a27769b1b9a532ec76690e8df57b8228691a5b40d5be6b8fbe9"
      url "https://github.com/primissus/zjump/releases/download/v#{version}/zjump_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "4c564bbc381b25d425ba7ec6612f4803ff69137a9af8d8292f8be85f73886c84"
      url "https://github.com/primissus/zjump/releases/download/v#{version}/zjump_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "115b5cffc04a5b267ed2c9be98dcdc2de87c3d8f8cd63e0527a5501a4aa621cc"
      url "https://github.com/primissus/zjump/releases/download/v#{version}/zjump_#{version}_linux_amd64.tar.gz"
    end
  end

  name "zjump"
  desc "Frecency-based directory-jumping CLI tool (Go reimplementation of zoxide)."
  homepage "https://github.com/primissus/zjump"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zjump"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/zjump"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Add the shell hook to your rc file, e.g.:
      eval "$(zjump init bash)"   # or: zjump init zsh
  EOS
end
